version: '3'


services:
  webServer:
    image: nginx
    ports:
      - "80:8080"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs:/var/log/nginx
      - ./html/:/usr/share/nginx/html:ro