version: '3'

services:
  
  webServer:
    image: nginx
    container_name: nginx1
    hostname: ng1
    ports:
      - 80:80
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - internal
    depends_on:
      - nodeapp1
      - nodeapp2
      - nodeapp3
      - nodeapp4


  nodeapp1:
    image: nodeapp2
    container_name: nodeapp1
    hostname: nodeapp1
    networks:
      - internal
    environment:
      - APPID=1111
    ports:
      - 1111:9999

  nodeapp2:
    image: nodeapp2
    container_name: nodeapp2
    hostname: nodeapp2  
    networks:
      - internal
    environment:
      - APPID=2222
    ports:
      - 2222:9999
    
  nodeapp3:
    image: nodeapp2
    container_name: nodeapp3
    hostname: nodeapp3
    networks:
      - internal
    environment:
      - APPID=3333
    ports:
      - 3333:9999

  nodeapp4:
    image: nodeapp2
    container_name: nodeapp4
    hostname: nodeapp4
    networks:
      - internal
    environment:
      - APPID=4444
    ports:
      - 4444:9999

    


networks:
  internal:
      name: internal
      driver: bridge
      attachable: true

