version: '3'

services:
  
  webServer1:
    image: nginx
    container_name: nginx1
    hostname: ng1
    ports:
      - 80:8080
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - internal
    depends_on:
      - nodeapp1
      - nodeapp2
      - nodeapp3


  webServer2:
    image: nginx
    container_name: nginx2
    hostname: ng1
    ports:
      - 81:8080
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - internal
    depends_on:
      - nodeapp1
      - nodeapp2
      - nodeapp3

  nodeapp1:
    image: nodeapp
    container_name: nodeapp1
    hostname: nodeapp1
    networks:
      - internal

  nodeapp2:
    image: nodeapp
    container_name: nodeapp2
    hostname: nodeapp2  
    networks:
      - internal

  nodeapp3:
    image: nodeapp
    container_name: nodeapp3
    hostname: nodeapp3
    networks:
      - internal

networks:
  internal:
      name: internal
      driver: bridge
      attachable: true

